server:
  port: 8091
spring:
  application:
    name: publisher-service
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    client: nacos
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  scan:
    base-packages: com.best.dubbo.publisher.service
demo:
  service:
    version: 1.0.0
