# Use root/example as user/password credentials
version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"