spring:
  datasource:
    username: root
    password: Wang931125
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://119.91.232.58:3307/test?useUnicode=true&characterEncoding=utf8
server:
  port: 8091
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml