server:
  port: 12382
  servlet:
    session:
      timeout: 10m
spring:
  redis:
    database: 1
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: info
