server:
  port: 8092
spring:
  boot:
    admin:
      client:
        url: http://192.168.5.147:8091
        instance:
          prefer-ip: true
          service-url: http://192.168.5.147:8092
  application:
    name: demo1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always