# Use root/example as user/password credentials
version: '3.8'

services:
  db:
    image: mysql:8.0.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test