server:
  port: 9090
spring:
  flyway:
    enabled: false
  datasource:
    database-address: jdbc:mysql://localhost:3306/
    database-name: test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.database-address}${spring.datasource.database-name}?useUnicode=true&characterEncoding=utf8
    dynamic:
      hikari:  # 全局hikariCP参数，所有值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        ## 最小空闲连接数量
        min-idle: 1
        ## 连接池最大连接数，默认是15
        max-pool-size: 1
        ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        is-auto-commit: true
        ## 空闲连接存活最大时间，默认600000（10分钟）
        idle-timeout: 30000
        ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        max-lifetime: 1800000
        ## 数据库连接超时时间,默认30秒，即30000
        connection-timeout: 3000
        connection-test-query: SELECT 1
