server:
  port: 12922
spring:
  datasource:
    username: root
    password: Wang931125
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.232.58:3306/test?useUnicode=true&characterEncoding=utf8

