server:
  port: 9999
  servlet:
    context-path: /
    session:
      timeout: 9000

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://35.234.43.150:3306/task?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Wang931125!
          driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    db-history-used: true
    history-level: full
    check-process-definitions: false


