# Use root/example as user/password credentials
version: '3.8'

services:
  neo4j:
    image: neo4j
    environment:
      NEO4J_AUTH: 'neo4j/123456'
    ports:
      - "7687:7687"
      - "7474:7474"
