server:
  port: 9995
spring:
  application:
    name: comsumer-service
dubbo:
  application:
    metadata-type: composite
  registry:
    address: zookeeper://127.0.0.1:2181?registry-type=service
    simplified: true
  consumer:
    check: off
demo:
  service:
    version: 1.0.0
