server:
  port: 9995
spring:
  application:
    name: comsumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.110:2222
        namespace: 6e837751-c70c-491c-8e2d-e9bfbbfca7fd
      config:
        import-check:
          enabled: false
dubbo:
  application:
    name: comsumer-service
  metadata-report:
    address: nacos://skyline-nacos.skyline-account.svc.dev.local:8848
    username: nacos
    password: nacos
    parameters:
      namespace: dubbo
  registry:
    simplified: true
    client: nacos
    address: nacos://skyline-nacos.skyline-account.svc.dev.local:8848
    username: nacos
    password: nacos
    use-as-config-center: true
    use-as-metadata-center: true
    parameters:
      namespace: dubbo
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
    timeout: 30000
demo:
  service:
    version: 1.0.0
