server:
  port: 8093
spring:
  application:
    name: comsumer-service
dubbo:
  application:
    metadata-type: composite
  registry:
    client: nacos
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
    simplified: true
  consumer:
    check: off
demo:
  service:
    version: 1.0.0
